# -----------------------------
# Stage 1 — Dependencies
# -----------------------------
FROM node:20-alpine AS deps

WORKDIR /app

# Install dependencies required for Prisma
RUN apk add --no-cache openssl

COPY package*.json ./

RUN npm install --omit=dev


# -----------------------------
# Stage 2 — Build
# -----------------------------
FROM node:20-alpine AS builder

WORKDIR /app

RUN apk add --no-cache openssl

COPY --from=deps /app/node_modules ./node_modules

COPY package*.json ./
COPY prisma ./prisma
COPY src ./src

# Generate Prisma client
RUN npx prisma generate


# -----------------------------
# Stage 3 — Production
# -----------------------------
FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl

ENV NODE_ENV=production

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/src ./src
COPY package*.json ./

EXPOSE 3008

# Run migrations then start server
CMD ["sh", "-c", "npx prisma migrate deploy && node ./order-service/server.js"]