export const ORDER_STATUS = {
  PENDING:            'PENDING',
  CHECKOUT_INITIATED: 'CHECKOUT_INITIATED',
  PROCESSING:         'PROCESSING',
  SHIPPED:            'SHIPPED',
  DELIVERED:          'DELIVERED',
  CANCELLED:          'CANCELLED',
};

export const TERMINAL_STATES = new Set([
  ORDER_STATUS.DELIVERED,
  ORDER_STATUS.CANCELLED,
]);

export const VALID_TRANSITIONS = {
  [ORDER_STATUS.PENDING]:            [ORDER_STATUS.CHECKOUT_INITIATED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.CHECKOUT_INITIATED]: [ORDER_STATUS.PROCESSING,         ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PROCESSING]:         [ORDER_STATUS.SHIPPED,            ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.SHIPPED]:            [ORDER_STATUS.DELIVERED],
  [ORDER_STATUS.DELIVERED]:          [],
  [ORDER_STATUS.CANCELLED]:          [],
};
